import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {dirname} from 'node:path';
import {Models} from '/Users/server/dev/yap-video-editing/packages/core/src/models.ts';
import {jsonWorker} from '/Users/server/dev/yap-video-editing/apps/service/src/worker.ts';
const b='/tmp/yap-editing-speaker-replication';const d=b+'/fluidaudio-feasibility';
const p=JSON.parse(await readFile(d+'/protocol.json','utf8'));const manifest=JSON.parse(await readFile(d+'/manifest.json','utf8'));const hash=(x:Buffer)=>createHash('sha256').update(x).digest('hex');
assert.equal(hash(await readFile(b+'/fluidaudio-reference/Sources/Reference/main.swift')),p.workerSourceSha256);assert.equal(hash(await readFile(d+'/manifest.json')),p.manifestSha256);
const models=new Models(b+'/fluidaudio-model-library',globalThis.fetch,[manifest]);assert.equal((await models.status(manifest.name)).state,'ready');
const modelRoot=dirname(JSON.parse(await readFile(d+'/preparation.json','utf8')).modelDirectory);
await mkdir(b+'/fluidaudio-cache/tmp',{recursive:true});await mkdir(b+'/fluidaudio-cache/home',{recursive:true});
const executable=b+'/fluidaudio-reference/.build/release/Reference';
await writeFile(d+'/execution-r3.json',JSON.stringify({binarySha256:hash(await readFile(executable)),modelRoot,networkDenied:true,originalSourceReadsDenied:true,providerModelsVerified:true,sourceReadAtRuntime:false},null,2),{flag:'wx'});
const sandbox='(version 1)(allow default)(deny network*)(deny file-read* (subpath "/Users/server/dev/screen-recorder"))(deny file-read* (subpath "/Users/server/dev/yap-video-editing"))(deny file-read* (subpath "/Users/server/dev/videos"))';
const environment={...process.env,TMPDIR:b+'/fluidaudio-cache/tmp',XDG_CACHE_HOME:b+'/fluidaudio-cache'};
const start=performance.now();const worker=jsonWorker({executable:'/usr/bin/sandbox-exec',args:['-p',sandbox,executable],environment},180000);
const result=await worker('speaker.community1Reference',{modelDirectory:modelRoot,cases:p.cases.map(({id,pcm,pcmSha256,frames,output}:any)=>({id,pcm,pcmSha256,frames,output}))});
await writeFile(d+'/transport-r3.json',JSON.stringify({result,wallSeconds:(performance.now()-start)/1000,networkDenied:true},null,2),{flag:'wx'});await models.settled();assert.equal(result.ok,true,JSON.stringify(result));console.log(JSON.stringify(result));
