runElapsedFormatTests()
runSelectionTests()
runAwaitedMicrophoneTests()
runStartRequestTests()
runMenuStateTests()
runRecentStorageTests()
runExportTests()
runShortcutTests()
runRegionSelectionTests()
runStartPermissionTests()
runPermissionRowTests()
runSettingsActionTests()
runPreferenceTests()
runRecordingOverlayTests()
runCountdownTests()
print("PASS recording controls")
