runElapsedFormatTests()
runSelectionTests()
runStartRequestTests()
runMenuStateTests()
runRecentStorageTests()
runExportTests()
runShortcutTests()
runRegionSelectionTests()
print("PASS recording controls")
