node /Users/david/dev/screen-recorder/apps/cli/dist/main.js --help > /tmp/screenrec-image-skill-M1kDJn/agent-output/help.json
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js asset.import --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - < /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-import.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-import.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-import.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js asset.import --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - < /tmp/screenrec-image-skill-M1kDJn/agent-output/card-import.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/card-import.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/card-import.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js job.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - < /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-job.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-job.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-job.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js job.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - < /tmp/screenrec-image-skill-M1kDJn/agent-output/card-job.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/card-job.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/card-job.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js asset.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - < /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-asset.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-asset.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-asset.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js asset.origins --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - < /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-origins.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-origins.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-origins.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js asset.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - < /tmp/screenrec-image-skill-M1kDJn/agent-output/card-asset.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/card-asset.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/card-asset.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js asset.origins --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - < /tmp/screenrec-image-skill-M1kDJn/agent-output/card-origins.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/card-origins.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/card-origins.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js frame.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - --output /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-full.png < /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-full-1.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-full-1.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-full-1.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js frame.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - --output /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-small.png < /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-small-1.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-small-1.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-small-1.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js frame.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - --output /tmp/screenrec-image-skill-M1kDJn/agent-output/card-full.png < /tmp/screenrec-image-skill-M1kDJn/agent-output/card-full-1.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/card-full-1.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/card-full-1.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js frame.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - --output /tmp/screenrec-image-skill-M1kDJn/agent-output/card-small.png < /tmp/screenrec-image-skill-M1kDJn/agent-output/card-small-1.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/card-small-1.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/card-small-1.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js frame.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - --output /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-full.png < /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-full-2.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-full-2.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-full-2.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js frame.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - --output /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-small.png < /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-small-2.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-small-2.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/diagram-small-2.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js frame.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - --output /tmp/screenrec-image-skill-M1kDJn/agent-output/card-full.png < /tmp/screenrec-image-skill-M1kDJn/agent-output/card-full-2.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/card-full-2.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/card-full-2.stderr.txt
node /Users/david/dev/screen-recorder/apps/cli/dist/main.js frame.get --socket /tmp/screenrec-image-skill-M1kDJn/library/run/service.sock --params - --output /tmp/screenrec-image-skill-M1kDJn/agent-output/card-small.png < /tmp/screenrec-image-skill-M1kDJn/agent-output/card-small-2.request.json > /tmp/screenrec-image-skill-M1kDJn/agent-output/card-small-2.response.json 2> /tmp/screenrec-image-skill-M1kDJn/agent-output/card-small-2.stderr.txt
