import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {Models} from '/Users/server/dev/yap-video-editing/packages/core/src/models.ts';
import {jsonWorker} from '/Users/server/dev/yap-video-editing/apps/service/src/worker.ts';
const b='/tmp/yap-editing-alignment-replication';const d=b+'/fluid-ctc110';const p=JSON.parse(await readFile(d+'/protocol.json','utf8'));const m=JSON.parse(await readFile(d+'/manifest.json','utf8'));const sha=(x:Buffer)=>createHash('sha256').update(x).digest('hex');assert.equal(sha(await readFile(b+'/fluid-reference/Sources/EmissionReference/main.swift')),p.workerSourceSha256);assert.equal(sha(await readFile(d+'/manifest.json')),p.manifestSha256);const models=new Models(b+'/model-library',globalThis.fetch,[m]);assert.equal((await models.status(m.name)).state,'ready');const prep=JSON.parse(await readFile(d+'/preparation.json','utf8'));const exe=b+'/fluid-reference/.build/release/EmissionReference';
await mkdir(b+'/cache/tmp',{recursive:true});const environment={...process.env,TMPDIR:b+'/cache/tmp',XDG_CACHE_HOME:b+'/cache'};const sandbox='(version 1)(allow default)(deny network*)(deny file-read* (subpath "/Users/server/dev/screen-recorder"))(deny file-read* (subpath "/Users/server/dev/yap-video-editing"))(deny file-read* (subpath "/Users/server/dev/videos"))';
await writeFile(d+'/execution.json',JSON.stringify({binarySha256:sha(await readFile(exe)),networkDenied:true,repoReadsDenied:true,providerModelsVerified:true},null,2),{flag:'wx'});
const worker=jsonWorker({executable:'/usr/bin/sandbox-exec',args:['-p',sandbox,exe],environment},180000);const start=performance.now();const result=await worker('speech.ctcEmissionReference',{modelDirectory:prep.modelDirectory,cases:p.cases.map(({id,pcm,pcmSha256,frames,output,texts}:any)=>({id,pcm,pcmSha256,frames,output,texts}))});await writeFile(d+'/transport.json',JSON.stringify({result,wallSeconds:(performance.now()-start)/1000,networkDenied:true},null,2),{flag:'wx'});await models.settled();assert.equal(result.ok,true,JSON.stringify(result));console.log(JSON.stringify(result));
