import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {foldWord} from '/Users/server/dev/yap-video-editing/packages/core/src/word-kind.ts';
import {correspond} from './correspondence-reference.ts';
const b='/tmp/yap-editing-alignment-replication',dir=b+'/nemo-ctc110-correspondence',sha=(v:Buffer)=>createHash('sha256').update(v).digest('hex');
const source=b+'/nemo-ctc110/protocol-r2.json',p=JSON.parse(await readFile(source,'utf8'));
const recipe={status:'frozen-before-correspondence-analysis',emissionRecipeSha256:sha(await readFile(source)),arithmeticSourceSha256:sha(await readFile(b+'/correspondence-reference.ts')),producerSha256:sha(await readFile(b+'/invoke-correspondence.ts')),normalizationOwner:'/Users/server/dev/yap-video-editing/packages/core/src/word-kind.ts',normalizationSha256:sha(await readFile('/Users/server/dev/yap-video-editing/packages/core/src/word-kind.ts')),normalization:'core foldWord exact lowercase and edge punctuation trim; no stemming, numeral expansion or fragment guessing',policy:'All-optimal word-level ordered LCS. A match must be a unique pair in every optimal correspondence, with neither occurrence omissible. No possible correspondence unmatched; possible nonunique correspondence unknown. Greedy extras remain observed_extra/unknown with native intervals. Match is provider textual correspondence, not independent lexical ground truth.',bounds:'Supplied forced path estimates stay conditional. Original .08s/1280-sample frame-cell bounds retained; any token/observed word entering unowned PCM cells has refused_unowned_support. No clamp.',confidence:null,partialFragment:'Provider strings can correspond but partial lexical interpretation remains unknown; no phonetic prefix identity claim.',modelsDownloaded:false,inferenceRuns:0};await writeFile(dir+'/protocol.json',JSON.stringify(recipe,null,2),{flag:'wx'});
function words(tokens:any[],vocab:any){let text='';const chunks=tokens.map((t:any)=>{const start=text.length;const piece=vocab[String(t.token)].replaceAll('▁',' ');text+=piece;return {...t,charStart:start,charEnd:text.length,piece};});return [...text.matchAll(/\S+/g)].map(m=>{const ts=chunks.filter(t=>t.charStart<m.index!+m[0].length&&t.charEnd>m.index!);return {text:m[0],tokens:ts,startFrame:Math.min(...ts.map(t=>t.startFrame)),endFrame:Math.max(...ts.map(t=>t.endFrame))};});}
const reports=[];
for(const c of p.cases){const raw=JSON.parse(await readFile(c.output,'utf8')),a=JSON.parse(await readFile(b+'/nemo-ctc110-alignment/'+c.id+'.json','utf8'));const runs=[];let previous=-1;for(let f=0;f<raw.logProbs.length;f++){const row=raw.logProbs[f];let t=0;for(let k=1;k<row.length;k++)if(row[k]>row[t])t=k;if(t!==raw.blankId){if(t===previous)runs.at(-1)!.endFrame=f+1;else runs.push({token:t,startFrame:f,endFrame:f+1});}previous=t;}
 const observed=words(runs,raw.vocabulary),cs=[];
 for(const q of a.candidates){const supplied=q.text.split(/\s+/).filter(Boolean),groups=words(q.spans,raw.vocabulary),mapping=correspond(supplied,observed.map(w=>w.text));assert.equal(groups.length,supplied.length,`native grouping ${c.id}/${q.text}`);
  const requested=mapping.requested.map((r:any,i:number)=>{const pair=r.observedIndices.length===1?mapping.observed[r.observedIndices[0]]:null;const status=r.status==='matched'&&pair?.status!=='matched'?'unknown':r.status;const w=groups[i];return {...r,status,nativeDecodedTarget:w.text,nativeTokenizationUnknown:w.tokens.some(t=>t.token===0),providerInterpretation:'Observed greedy textual correspondence only; no lexical ground truth claim',estimatedBounds:{startSeconds:w.startFrame*.08,endSeconds:w.endFrame*.08,startFrame:w.startFrame,endFrame:w.endFrame,interpretation:'conditional supplied-text CTC path, not phonetic boundaries'},physicalAdmission:w.endFrame*1280>c.frames?'refused_unowned_support':'within_source_support',confidence:null,tokens:w.tokens.map(t=>({token:t.token,startFrame:t.startFrame,endFrame:t.endFrame,correspondence:status,physicalAdmission:t.endFrame*1280>c.frames?'refused_unowned_support':'within_source_support'}))};});
  cs.push({text:q.text,optimum:mapping.optimum,requested,observed:mapping.observed.map((r:any,i:number)=>({...r,nativeTokens:observed[i].tokens.map(t=>t.token),startFrame:observed[i].startFrame,endFrame:observed[i].endFrame,physicalAdmission:observed[i].endFrame*1280>c.frames?'refused_unowned_support':'within_source_support',confidence:null})),partialLexicalInterpretation:c.id==='false-start'||c.id==='fortunate-truncated'?'unknown':'not_inferred'});
 }
 const report={id:c.id,sourceFrames:c.frames,sourceEmissionSha256:sha(await readFile(c.output)),arithmeticReportSha256:sha(await readFile(b+'/nemo-ctc110-alignment/'+c.id+'.json')),greedyText:a.greedyText,candidates:cs};await writeFile(dir+'/'+c.id+'.json',JSON.stringify(report,null,2),{flag:'wx'});reports.push({id:c.id,candidates:cs.map(q=>({text:q.text,requested:q.requested.map(r=>r.status),observedExtras:q.observed.filter(r=>r.status!=='matched').map(r=>({index:r.index,text:r.text,status:r.status}))}))});
}
await writeFile(dir+'/summary.json',JSON.stringify({reports,inferenceRuns:0,acceptedScope:'provider text correspondence with conditional estimated timing and separate physical admission; no confidence calibration or partial lexical claim'},null,2),{flag:'wx'});
console.log(JSON.stringify(reports));
