try await runCaptureTerminationTests()
try runCaptureWriterTests()
runCaptureClockTests()
await runHeldTailFrameTests()
try await runCaptureJournalTests()
try await runDeferredPauseTests()
try runCursorGeometryTests()
try await runMediaRecoveryTests()
